name = "gun-peer-server"
main = "src/worker.js"
compatibility_date = "2026-05-14"

assets = { directory = "./public", binding = "ASSETS" }

[[durable_objects.bindings]]
name = "GUN_PEER"
class_name = "GunPeerObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GunPeerObject"]

[vars]
STORAGE_EVICT_AT_BYTES = "9663676416"
STORAGE_EVICT_BYTES = "1073741824"
